# -*- coding: utf-8 -*-
"""basics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDxK4pd7p13ueSOrIBmOeYGmiGjHdLOP
"""

# first print screen
print("aqdas")

#basic maths
x = 5
y = 2
print(x // y)

#math functions
import math
math.ceil(7.15)
math.floor(7.99)

#user input
a="aqdas"
b=2
c=2.1
d=int(input("enter value of d;"))#input is always a string in python unless specific data type mentioned
print(a,b,c,d)