# -*- coding: utf-8 -*-
"""week1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDxK4pd7p13ueSOrIBmOeYGmiGjHdLOP
"""

#loops
#for loop is used where iterations are known
for i in range(2):#iterates i from 0 to range-1
 print(i)

#while loop
i=0#number of iterations are unknown
while(i<3):
    if(i==1):
     break
    i=i+1
    print(i)

#if-else ,elif,elif nested
a=int(input('enter age;'))
if(a<20):
 print("teenager")
elif(a==20):
 print("adult")
elif(a>20):
 print("more than 20")
else:
 print(a)

#for loop and if-else
a=int(input("enter your age;"))
for a in range(1,5):
 print (a)
 if(a<18):
  print("not eligible")
 else:
  print("eligible to apply")

#functions
def calculategmean(a,b):
    mean=(a+b)/(a-b)
    print(mean)

a=2
b=9
calculategmean(a,b)
c=3
d=7
calculategmean(c,d)
f=9
h=6
calculategmean(9,6)

#even odd check
#input
i=2
#function
def is_even(a):
 if(a%2==0):
     return True
 else:
    return False
    #output
print(is_even(i))

#MINI CHALLENGE
i=int(input("enter the computer secret number:"))
if(i>7):
    print("too high")
elif(i>7):
    print("too low")
elif(i==7):
    print(correct)

#PRIME NUMBER CHECK
def is_prime(number):
    if(number<=0):
      return False
    for i in range(2, number):
        if (number % i) == 0:
            return False
    return True

num=int(input("enter a number"))
if is_prime(num):
    print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")

#GUESSING GAME
num=9
while True:
 i=int(input("enter your guess:"))
 if(i<num):
    print("too low")
 elif(i>num):
    print("too high")
 else:
    print("guess is correct")
    break

#table generator
num=int(input("enter the number for which u wanna generate table:"))
for i in range(1,11):
    print(num, "*", i, "=", i * num)